# Generated by Django 5.0.3 on 2025-04-30 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_expense_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='description',
        ),
    ]
