# Generated by Django 5.0.3 on 2025-04-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_budget_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='is_deduction',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='is_income',
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
