# Generated by Django 5.0.3 on 2025-04-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_expense_is_deduction_remove_expense_is_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
