# Generated by Django 5.0.3 on 2025-05-08 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_expense_date_total_expense'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Total_expense',
        ),
    ]
